%% renameColumns
% replaces raw column names from google form response data with more
% readable ones.

function dataTable = renameColumns(dataTable)

oldColNames = ["AtWhichResearchInstitutionAreYouAStudentOrStaffMember_",...
                "WhichOfTheseTermsBestDescribeYourCareerStageOrRole__selectOneOr",...
                "HowWouldYouDescribeYourMATLABExperience__UsingTermsDefinedByThe",...
                "PleaseAddAnyAdditionalDetailIfYouWish",...
                "HowWouldYouDescribeYourExperienceOfSoftwareDevelopmentAndCodeIn",...
                "PleaseAddAnyAdditionalDetailIfYouWish_1",...
                "PleaseIndicateWhetherYouAreAwareOfTheFollowingConceptsInResearc",...
                "PleaseIndicateWhetherYouAreAwareOfTheFollowingConceptsInResea_1",...
                "PleaseIndicateWhetherYouAreAwareOfTheFollowingConceptsInResea_2",...
                "PleaseIndicateWhetherYouAreAwareOfTheFollowingConceptsInResea_3",...
                "PleaseIndicateWhetherYouAreAwareOfTheFollowingConceptsInResea_4",...
                "PleaseIndicateWhetherYouAreAwareOfTheFollowingConceptsInResea_5",...
                "PleaseIndicateWhetherYouAreAwareOfTheFollowingConceptsInResea_6",...
                "PleaseIndicateWhetherYouAreAwareOfTheFollowingConceptsInResea_7",...
                "DoYouUseGitAsAVersionControlSystemWithMATLAB_IfSo_WhichInterfac",...
                "WhichOfTheFollowingMATLABToolsAndLanguageFeaturesDoYouUse_",...
                "OfTheseTools_PleaseIndicateWhetherYouWouldLikeToLearnAboutThemA",...
                "OfTheseTools_PleaseIndicateWhetherYouWouldLikeToLearnAboutThe_1",...
                "OfTheseTools_PleaseIndicateWhetherYouWouldLikeToLearnAboutThe_2",...
                "OfTheseTools_PleaseIndicateWhetherYouWouldLikeToLearnAboutThe_3",...
                "OfTheseTools_PleaseIndicateWhetherYouWouldLikeToLearnAboutThe_4",...
                "OfTheseTools_PleaseIndicateWhetherYouWouldLikeToLearnAboutThe_5",...
                "OfTheseTools_PleaseIndicateWhetherYouWouldLikeToLearnAboutThe_6",...
                "InGeneral_WhichTrainingFormatsDoYouFavourForLearningCoding_soft",...
                "WhenYouSeekGuidanceInWritingCode_WhereDoYouTurnTo_"];

newColNames = ["institution",...
                "role",...
                "matlabExperience",...
                "matlabExperienceAdditionalInfo",...
                "programmingExperience",...
                "programmingExperienceAdditionalInfo",...
                "awareness_versionControl",...
                "awareness_github",...
                "awareness_dependencyMgmt",...
                "awareness_CICD",...
                "awareness_literateProgramming",...
                "awareness_docGen",...
                "awareness_dataAvailability",...
                "awareness_softwareTesting",...
                "gitUsage",...
                "matlabFeatures",...
                "trainingDemand_projects",...
                "trainingDemand_testing",...
                "trainingDemand_livescripts",...
                "trainingDemand_versioncontrol",...
                "trainingDemand_customtoolboxes",...
                "trainingDemand_publishingcode",...
                "trainingDemand_licensing",...
                "generalTrainingPreferences",...
                "preferredGuidance"];

dataTable = renamevars(dataTable, oldColNames, newColNames);
end

